### ISSUE TITLE
Cannot do an exception of a POST route having apostrophe-headless

### ISSUE THREAD

**Issue by Jose96GIT** [apostrophecms/apostrophe-headless#35]
I wanted to have a CSRF exception in a POST route an I noticed that it fails when apostrophe-headless is active, so I attach this little project to show you the problem.

Launching this project the POST request to '/test' will be reject, but if you comment 'apostrophe-headless: {}' in app.js it will work.

Is there any way to do this having apostrophe-headless activated?

[project.zip](https://github.com/apostrophecms/apostrophe-headless/files/3008273/project.zip)

**Comment by boutell** [comment]
Hi Jose, I see no attachment?

**Comment by Jose96GIT** [comment]
Sorry @boutell, now I've attached it.

**Comment by cansoysal** [comment]
I have the same problem.

**Comment by boutell** [comment]
There is a PR in review. Thanks for pointing out the issue.
