### ISSUE TITLE
api:'editPermissionRequired' not working while fetching by id

### ISSUE THREAD

**Issue by arthurlefevre** [apostrophecms/apostrophe-headless#40]
When fetching multiple, for example, products with `/api/v1/products`, the fields having `api:'editPermissionRequired'` are not included (normal behaviour). However, when fetching one by id (`/api/v1/products/cxxxxx`), the said fields are included even if not logged ; it seems the check for permission is not done in `get one`(line 110 of apostrophe-pieces-headless/index.js)  and should be moved in the method `findForRestApi` (line 305 of apostrophe-pieces-headless/index.js).

**Comment by punkhub** [comment]
Thank you for the report. BTW are you working with one of our Enterprise
clients? That is not a requirement for work to be done in this issue, it is
just helpful for us to know.

**Comment by boutell** [comment]
Fix published as 2.9.2.
